2021-04-05 09:37:52.836 [error] <0.1162.0> CRASH REPORT Process <0.1162.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Broadway was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :permanent,\n      ...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2021-04-05 09:37:55.494 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Broadway was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :permanent,\n      ...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2021-04-05 09:38:35.271 [error] <0.635.0> CRASH REPORT Process <0.635.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,econnrefused}},[{'Elixir.ApiServerWeb.TranslationRPC',call,1,[{file,"lib/api_server_web/translations_rpc.ex"},{line,9}]},{'Elixir.ApiServerWeb.Resolvers.Translation',translate,3,[{file,"lib/api_server_web/resolvers/translation.ex"},{line,3}]},{'Elixir.Absinthe.Resolution',call,2,[{file,"lib/absinthe/resolution.ex"},{line,209}]},{'Elixir.Absinthe.Phase.Document.Execution.Resolution',reduce_resolution,1,[{file,...},...]},...]},...},...},...}
2021-04-05 09:38:35.274 [error] <0.635.0> Cowboy stream 5 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.624.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,econnrefused}},[{'Elixir.ApiServerWeb.TranslationRPC',call,1,[{file,"lib/api_server_web/translations_rpc.ex"},{line,9}]},{'Elixir.ApiServerWeb.Resolvers.Translation',translate,3,[{file,"lib/api_server_web/resolvers/translation.ex"},{line,3}]},{'Elixir.Absinthe.Resolution',call,2,[{file,"lib/absinthe/resolution.ex"},{line,209}]},{'Elixir.Absinthe.Phase.Document.Execution.Resolution',reduce_resolution,1,[{file,"..."},...]},...]},...},...}
2021-04-05 09:56:45.188 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: :ok}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok, ...">>},...},...},...},...}
2021-04-05 09:56:45.190 [error] <0.652.0> Cowboy stream 1 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: :ok}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok, an...">>},...},...},...}
2021-04-05 09:56:54.090 [error] <0.694.0> CRASH REPORT Process <0.694.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:56:54.090 [error] <0.694.0> Cowboy stream 2 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:57:20.424 [error] <0.736.0> CRASH REPORT Process <0.736.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:57:20.424 [error] <0.736.0> Cowboy stream 3 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:57:21.822 [error] <0.778.0> CRASH REPORT Process <0.778.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:57:21.822 [error] <0.778.0> Cowboy stream 4 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:57:34.142 [error] <0.795.0> CRASH REPORT Process <0.795.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:57:34.143 [error] <0.795.0> Cowboy stream 5 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:57:38.385 [error] <0.811.0> CRASH REPORT Process <0.811.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:57:38.385 [error] <0.811.0> Cowboy stream 6 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:58:00.361 [error] <0.827.0> CRASH REPORT Process <0.827.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:58:00.362 [error] <0.827.0> Cowboy stream 7 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:58:01.554 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:58:01.554 [error] <0.843.0> Cowboy stream 8 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:58:03.270 [error] <0.859.0> CRASH REPORT Process <0.859.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:58:03.271 [error] <0.859.0> Cowboy stream 9 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.651.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 09:58:11.123 [error] <0.618.0> CRASH REPORT Process <0.618.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:o...">>},...},...},...},...}
2021-04-05 09:58:11.125 [error] <0.618.0> Cowboy stream 2 with ranch listener 'Elixir.ApiServerWeb.Endpoint.HTTP' and connection process <0.614.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Absinthe.ExecutionError',message => <<"Invalid value returned from resolver.\n\nResolving field:\n\n    translate\n\nDefined at:\n\n    /home/mads/mygit/scalable-ml-service/api_server/lib/api_server_web/schema.ex:11\n\nResolving on:\n\n    %{}\n\nGot value:\n\n    %{translated_string: \"Lala\"}\n\n...\n\nDid you forget to return a valid `{:ok, any}` | `{:error, error_value}` tuple?\n\n...\n\nThe result must be one of the following...\n\n## For a data result\n\n`{:ok,...">>},...},...},...}
2021-04-05 10:03:31.320 [error] <0.656.0> gen_server <0.656.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-05 10:03:31.337 [error] <0.656.0> CRASH REPORT Process <0.656.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-05 10:03:31.337 [error] <0.655.0> Supervisor {<0.655.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38491 -> 127.0.0.1:5672">>,1}) at <0.656.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-05 10:03:31.337 [error] <0.655.0> Supervisor {<0.655.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38491 -> 127.0.0.1:5672">>,1}) at <0.656.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-05 10:08:37.140 [error] <0.630.0> gen_server <0.630.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-05 10:08:37.147 [error] <0.630.0> CRASH REPORT Process <0.630.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-05 10:08:37.147 [error] <0.629.0> Supervisor {<0.629.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50285 -> 127.0.0.1:5672">>,1}) at <0.630.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-05 10:08:37.147 [error] <0.629.0> Supervisor {<0.629.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50285 -> 127.0.0.1:5672">>,1}) at <0.630.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-05 10:12:38.573 [error] <0.1210.0> gen_server <0.1210.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-04-05 10:12:38.573 [error] <0.1210.0> CRASH REPORT Process <0.1210.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-04-05 10:12:38.573 [error] <0.1209.0> Supervisor {<0.1209.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52803 -> 127.0.0.1:5672">>,1}) at <0.1210.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-04-05 10:12:38.573 [error] <0.1209.0> Supervisor {<0.1209.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52803 -> 127.0.0.1:5672">>,1}) at <0.1210.0> exit with reason reached_max_restart_intensity in context shutdown
2021-04-05 10:12:38.573 [error] <0.1211.0> gen_server <0.1211.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.1210.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-Pmb_GyxGiEwuTdv4CV3Rrw">>,1,false,<<>>,<<"amq.gen-u2IZtORB3txAdFHgeGSzbQ">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,undefined,undefined,<<"LTU3NjQ2MDc1MjMwMzQyMTgyMg==">>,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"lala b'Hej' lala 8">>}},60000]}} in gen_server2:call/3 line 346
